name: surya_cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - sunpy
  - xarray
  - dask
  - bottleneck
  - h5netcdf
  - hdf5plugin
  - pip
  - pip:
    - torch
    - torchvision
    - lightning
    - s3fs
    - einops